//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo34_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryMaster
    {
        public int Enquiry_Id { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string Enquiry_Message { get; set; }
        public Nullable<System.DateTime> Enquiry_DateTime { get; set; }
    }
}
