//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo34_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackMaster
    {
        public int Feedback_Id { get; set; }
        public string Submitted_By { get; set; }
        public string Topic { get; set; }
        public Nullable<int> Star_Rating { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Submitted_On { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
