//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo34_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginMaster
    {
        public string UserId { get; set; }
        public string User_Password { get; set; }
        public string User_Type { get; set; }
        public Nullable<bool> User_Status { get; set; }
        public Nullable<int> Login_Count { get; set; }
        public Nullable<System.DateTime> Last_Login_DateTime { get; set; }
    }
}
